# base
[[plugins]]
repo = 'Shougo/vimproc.vim'

# color/view
[[plugins]]
repo =  'fatih/molokai'
[[plugins]]
repo =  'mattn/emoji-vim'


# utils
### tpope product {{{
[[plugins]]
repo =  'tpope/vim-surround'
[[plugins]]
repo =  'tpope/vim-abolish'
### }}}

### Shougo product {{{
# [[plugins]]
# repo =  'Shougo/neocomplete.vim'
# [[plugins]]
# repo =  'Shougo/neosnippet'
# [[plugins]]
# repo =  'Shougo/neosnippet-snippets'
[[plugins]]
repo =  'Shougo/denite.nvim'
[[plugins]]
repo =  'Shougo/deoplete.nvim'
### }}}

### thinca product {{{
[[plugins]]
repo =  'thinca/vim-qfreplace'
[[plugins]]
repo =  'thinca/vim-visualstar'
[[plugins]]
repo =  'thinca/vim-quickrun'
[[plugins]]
repo =  'thinca/vim-ref'
### }}}

### kana product {{{
[[plugins]]
repo =  'kana/vim-operator-user'
[[plugins]]
repo =  'kana/vim-operator-replace'
[[plugins]]
repo =  'kana/vim-textobj-user'
[[plugins]]
repo =  'kana/vim-textobj-function'
[[plugins]]
repo =  'kana/vim-smartchr'
[[plugins]]
repo =  'kana/vim-smartinput'
### }}}

### etc product {{{
[[plugins]]
repo =  'fuenor/qfixgrep'
[[plugins]]
repo =  't9md/vim-quickhl'
[[plugins]]
repo =  'jceb/vim-hier'
[[plugins]]
repo =  'Lokaltog/vim-easymotion'
[[plugins]]
repo =  'kien/ctrlp.vim'
[[plugins]]
repo =  'scrooloose/syntastic'
[[plugins]]
repo =  'majutsushi/tagbar'
[[plugins]]
repo =  'mattn/emmet-vim'
[[plugins]]
repo =  'editorconfig/editorconfig-vim'
[[plugins]]
repo =  'AndrewRadev/switch.vim'
[[plugins]]
repo =  'osyo-manga/vim-operator-search'
[[plugins]]
repo =  'h1mesuke/vim-alignta'
[[plugins]]
repo =  'tomtom/tcomment_vim'
[[plugins]]
repo =  'vim-scripts/gtags.vim'
[[plugins]]
repo =  'zchee/deoplete-go'
build = 'make'
[[plugins]]
repo =  'ozelentok/denite-gtags'
### }}}


# coding
[[plugins]]
repo =  'tpope/vim-repeat'
### [[plugins]]
### repo =  'taku-o/vim-toggle'
### [[plugins]]
### repo =  'nathanaelkane/vim-indent-guides'


# git
[[plugins]]
repo =  'tpope/vim-fugitive'
[[plugins]]
repo =  'gregsexton/gitv'


# golang
[[plugins]]
repo =  'fatih/vim-go'
