#!/bin/bash
DOTFILES=$HOME/src/github.com/cowsys/dotfiles/


link() {
    rm -rf $HOME/$1;
    ln -s $DOTFILES/$1 $HOME/$1
}

## files
link .actrc
link .bash_profile
link .bashrc
link .gitconfig
link .gitignore
link .gitignore_global
link .gvimrc
link .ideavimrc
link .tmux.conf
link .vimrc
link .xvimrc
link .zshrc

## dirctories
link .config
link .vim/pack
link .vim/user
