#!/bin/bash
DOTFILES=$HOME/src/github.com/cowsys/dotfiles/


link() {
    rm -rf $HOME/$1;
    ln -s $DOTFILES/$1 $HOME/$1
}


link .bashrc
link .bash_profile
link .zshrc

link .tmux.conf

link .vimrc
link .gvimrc
link .ideavimrc

link .gitconfig
link .gitignore
link .gitignore_global

link .config

### homebrew
### homebrew softwares
brew install tmux
brew install vim --with-lua
brew install bash
brew install zsh
brew install peco
brew install hub
brew install ctags
#brew install zsh-completions
brew install bash-completion
brew install wget
brew install nkf
brew install tree
brew install lynx
brew install global
brew install httpie
brew install terminal-notifier

brew install kubernetes-cli

### go softwares
go get github.com/nsf/gocode
go get github.com/rogpeppe/godef
go get github.com/dgryski/vim-godef

### ghq
#### go
##### lib&sample&docs
ghq get https://github.com/GoogleCloudPlatform/golang-samples
ghq get https://github.com/GoogleCloudPlatform/gcloud-golang
