#!/bin/bash
DOTFILES=$HOME/src/github.com/cowsys/dotfiles/


link() {
    rm -rf $HOME/$1;
    ln -s $DOTFILES/$1 $HOME/$1
}


link .bashrc
link .bash_profile
link .zshrc

link .tmux.conf

link .vimrc
link .vim/user
link .vim/rc
link .gvimrc
link .ideavimrc

link .gitconfig
link .gitignore
link .gitignore_global

link .config

### homebrew
### homebrew softwares
brew install tmux
brew install vim --with-lua
brew install neovim
brew install bash
brew install zsh
brew install peco
brew install hub
brew install goenv

#brew install zsh-completions
brew install bash-completion
brew install wget
brew install nkf
brew install tree
brew install httpie
brew install terminal-notifier
brew install ripgrep
brew install caskroom/cask/brew-cask
brew cask install visual-studio-code

brew install kubernetes-cli

### go softwares
brew install reviewdog/tap/reviewdog
brew tap tcnksm/ehr
brew install ghr

go get github.com/nsf/gocode
go get github.com/rogpeppe/godef
go get github.com/dgryski/vim-godef

### ghq
