#!/bin/bash
DOTFILES=$HOME/src/github.com/cowsys/dotfiles/


link() {
    rm -rf $HOME/$1;
    ln -s $DOTFILES/$1 $HOME/$1
}


link .bashrc
link .bash_profile
link .zshrc

link .tmux.conf

link .vimrc
link .vim/user
link .vim/rc
link .gvimrc
link .ideavimrc

link .gitconfig
link .gitignore
link .gitignore_global

link .config

### homebrew
### homebrew softwares
brew tap caskroom/cask
brew install tmux
brew install vim --with-lua
brew install neovim/neovim/neovim
brew install bash
brew install zsh
brew install fish
brew install peco
brew install hub
brew install global --with-exuberant-ctags --with-pygments
brew install ctags
brew install goenv
brew install shellcheck

#brew install zsh-completions
brew install bash-completion
brew install wget
brew install nkf
brew install tree
brew install lynx
brew install global
brew install httpie
brew install terminal-notifier
brew install ripgrep

brew install kubernetes-cli


### homebrew cask
brew cask install 1password
brew cask install alfred
brew cask install charles
brew cask install clipy
brew cask install dash
brew cask install gogland
brew cask install google-cloud-sdk
brew cask install imageoptim
brew cask install intellij-idea
brew cask install iterm2
brew cask install jasper
brew cask install karabiner-elements
brew cask install kindle
brew cask install licecap
brew cask install macvim
brew cask install postman
brew cask install sequel-pro
brew cask install sizeup
brew cask install skitch
brew cask install slack
brew cask install sourcetree
brew cask install thunderbird
brew cask install witch


### go softwares
go get github.com/nsf/gocode
go get github.com/rogpeppe/godef
go get github.com/dgryski/vim-godef

### ghq
#### go
##### lib&sample&docs
ghq get https://github.com/GoogleCloudPlatform/golang-samples
ghq get https://github.com/GoogleCloudPlatform/gcloud-golang
